### ISSUE TITLE
file backed demand paging

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1113]

**Comment by wjhun** [comment]
See #1125. The page cache presently is only used as a transparent block device cache - and thus directly maps byte offsets to sector numbers. To support caching of file data on a per inode (fsfile) basis, a "mapper" closure could be specified on instantiation that could be used to map file offsets to sector numbers - e.g. using a table that is populated by the filesystem. This would allow organization of cache buffers by file offset rather than storage device offset, paving the way for file-backed user mappings.

**Comment by eyberg** [comment]
https://github.com/nanovms/nanos/issues/866
