### ISSUE TITLE
Rust - Actix.rs starter example unreachable

### ISSUE THREAD

**Issue by placrosse** [nanovms/nanos#1150]
from the page at:

https://actix.rs/docs/getting-started/   (note the bind change below)

```
use actix_web::{web, App, HttpResponse, HttpServer, Responder};

async fn index() -> impl Responder {
    HttpResponse::Ok().body("Hello world!")
}

async fn index2() -> impl Responder {
    HttpResponse::Ok().body("Hello world again!")
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .route("/", web::get().to(index))
            .route("/again", web::get().to(index2))
    })
    .bind("0.0.0.0:8080")?  // <=  changed from example
    .run()
    .await
}
```

Built and ran using instructions from the hello Rust sample, cross compiling to Linux MUSL target on a Mac.  Nanos examples for both hello, and http hello worked properly.  Could not get the above to work however.  No errors given, and it appears to be running, but accessing from local browser spins endlessly, with no data returned.  Above does work using plain `cargo run` and accessing as normal Mac target.

**Comment by eyberg** [comment]
this seems to work fine w/libc under linux but cross-compiling w/musl from instructions via https://github.com/nanovms/ops-examples/tree/master/rust/01-hello-world does seem to stall

it actually doesn't even load

**Comment by wjhun** [comment]
A massive delay on initialization was caused by the (very inefficient) ingesting of a large number of program elf symbols into the kernel's internal symbol table - however only for static executables (a bug lead to the ingest being skipped for dynamic executables). While a native rust build on linux produces a dynamic executable, the musl cross compile produces a static executable - which is why the flaw only appeared on the mac build.

#1151 addresses this by disabling the symbol ingest by default - something that should only be needed for debugging - though the unacceptable delay is a product of #1152
