### ISSUE TITLE
net/resolving perf issue with java 11 pkg

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1259]
https://github.com/nanovms/ops/issues/590

not sure what is going on here but it takes forever to to slurp down a webpage w/httpclient, maybe it's just another packaging issue or is it something deeper?

**Comment by francescolavra** [comment]
This performance issue is due in large part to the fact that the /usr/lib/jvm/java-11-openjdk-amd64/conf/security/java.security file specifies `/dev/random` as random seed source, and the kernel doesn't have that (so the JVM falls back to a much slower system/thread activity algorithm for generating random numbers).
To fix the above, in the java.security file replace `securerandom.source=file:/dev/random` with `securerandom.source=file:/dev/urandom` (or alternatively we would need to add `/dev/random` as special file in the kernel). This brings performance to a much more acceptable level when using KVM acceleration (and improves things considerably also without acceleration).
(By the way, we may want to add an empty /tmp dir and the /lib/x86_64-linux-gnu/libnsl.so.1 file to tha Java 11 package, because they are looked for by the JVM. But this doesn't seem to affect performance).

Another improvement could be obtained by implementing a read-ahead policy when faulting in on-demand memory pages: running the simple Java program at https://github.com/nanovms/ops/issues/590 with Nanos causes a large number (around 17000) of page fault interrupts, which may well be the main performance bottleneck. For comparison, the same program run natively on Linux after dropping the page cache causes around 600 major (requiring I/O) page faults.

**Comment by eyberg** [comment]
that's a killer find! thanks!

**Comment by eyberg** [comment]
the java_11.0.8 pkg was updated to reflect the /dev/urandom change and is night/day faster (even w/out accel) -> 

we can close this tkt in favor of https://github.com/nanovms/nanos/issues/1268 for the other work

**Comment by francescolavra** [comment]
It turns out the majority of page faults occurring when loading a large number of Java classes are due to anonymous memory being faulted-in, and so don't benefit from a read-ahead policy. But around 25% of page faults are on file-backed memory, and #1279 increases overall performance by around 10% when using KVM (without acceleration, the performance increase is not noticeable).
