### ISSUE TITLE
Handle GCP delete instance event

### ISSUE THREAD

**Issue by fabioDMFerreira** [nanovms/nanos#1349]
similar to #1065 

Deleting gcp instances takes a long time. I'm wondering whether GCP is waiting for some signal or is only a slower process.

**Comment by francescolavra** [comment]
In my tests, deleting a GCP instance via `ops instance delete` takes around 15 seconds, and I consider this to be normal.
Deleting a running instance via the GCP portal takes around 20 seconds (with either a Nanos image or a stock Debian image), and deleting a stopped instance via the GCP portal takes around 10 seconds (again, with either a Nanos image or a stock Debian image).
@fabioDMFerreira did you observe a deletion time much longer than 15 seconds with `ops instance delete`? If so, there could be a problem in Nanos but I'm unable to reproduce it with current master; otherwise, this time is normal and is due to internal processing in the GCP infrastructure, and I don't think there is anything we can do about it.

**Comment by fabioDMFerreira** [comment]
@francescolavra I'm not able to replicate either. It took to me 15 seconds as well.
