### ISSUE TITLE
Consider replacing TFS with a more robust filesystem

### ISSUE THREAD

**Issue by levex** [nanovms/nanos#150]
* What's the benefit of using TFS?
* Could we replace it with ext2 or even some FAT? (Licensing issues could come in play)

Benefits of switching over to ext2/whatever:
 * Implementing writable FS becomes much easier
 * Well-tested on-disk format
 * A driver might be portable over from some BSD.
 * Lots of documentation in case we get stuck
 * More robust userspace tools (think mkfs/fsck, nvm could use those too)

Thoughts?

**Comment by wjhun** [comment]
I think this issue was created with some weak assumptions in mind, so I'm going to close it. We can certainly revisit the inclusion of a VFS layer into the kernel in order to support additional mountpoints and other filesystem types, but tfs meets the requirements we need for a root fs / config store. As stated above: 

> the original intent behind tfs was to have a unified data space that we could use for configuration, management, monitoring, and data transfer. particularly in the distributed case where there are going to be multiple hypervisors. having a single model makes it quite a bit easier to uniformly apply things like security and transactional consistency.
