### ISSUE TITLE
Send stdout & stderr logs to cloud provider's native logging facility

### ISSUE THREAD

**Issue by rrs45** [nanovms/nanos#1543]
Please enable logging of nanos instances directly to cloud providers native logging facility,  like cloud logging for GCP and cloud watch for AWS.

This will save time & effort to setup & manage logging for nanos instances specifically.

**Comment by rrs45** [comment]
Is it possible to run golang binary as Klib? So we users can implement missing functionalities.

**Comment by francescolavra** [comment]
No, klibs are strictly tied to the kernel, and when loaded become part of the kernel itself. On the other hand, golang binaries are built to run on top of an operating system.
In order to run as a klib, a golang program would need a customized version of the golang runtime (customized specifically to interface with Nanos).

**Comment by francescolavra** [comment]
#1794 implements logging to the AWS native logging facility, i.e. CloudWatch

**Comment by eyberg** [comment]
https://github.com/nanovms/nanos/pull/1808

**Comment by eyberg** [comment]
both of these are now supported - closing
