### ISSUE TITLE
Lwip NOSYS 0 should be used

### ISSUE THREAD

**Issue by tijoytom-zz** [nanovms/nanos#164]
Right now we use Lwip with no OS mode, which is fine for now since we run only on single core.But eventually we want to use LWip with OS mode

**Comment by francescolavra** [comment]
As of now, all lwIP calls are made from code (syscalls, bottom halves, timers) under the kernel lock, and thus we are MP-safe.
If we want to take (some of) this code out of the kernel lock, I see two alternatives:
- switch to NO_SYS=0: this requires 1) adding support for kernel threads (because the lwIP core would be run from the `tcpip_thread`); 2) implementing synchronization primitives such as `sys_mutex_lock()` that would be called from lwIP; 3) wrap all lwIP calls in `LOCK_TCPIP_CORE()`/`UNLOCK_TCPIP_CORE()`, or alternatively modify them to use `tcpip_api_call()` (for example, instead of calling tcp_write(), we need to set up a struct holding function call argument values, implement a helper function that takes these values from the struct and calls tcp_write(), and call tcpip_api_call() by passing it the helper function pointer and the struct pointer)
- keep using NO_SYS=1, and implement our own locking (e.g. define a global lwIP spinlock, and use it at each lwIP call).

To me, the second alternative seems simpler and more efficient.
