### ISSUE TITLE
system crash on a clock call?

### ISSUE THREAD

**Issue by zeroecco** [nanovms/nanos#1781]
Had a production instance crash today based on what looks like the clock. it auto restarted and resumed.

output from ops: 

$ ops version
Ops version: 0.1.33
Nanos version: 0.1.42

the log from the unikernel
```
frame trace: 
ffffc0000583ff00:   ffffffff8009487a	(blockq_check_timeout + 000000000000006a/00000000000002e5)
ffffc0000583ff60:   ffffffff800da079	(nanosleep + 00000000000002a9/0000000000000406)
ffffc0000583ffb0:   ffffffff800d07c3	(syscall_handler + 00000000000002f3/00000000000005ec)
ffffc0000583fff0:   000617f7ae1fa154
0000000100693d30:   000000000044ba45
0000000100693da0:   0000000000443553
0000000100693dc8:   0000000000443499
0000000100693df8:   000000000046ee85
000000c0000069c8:   0000000100693dd8
assertion t >= last_raw failed at /home/eyberg/go/src/github.com/nanovms/nanos/src/runtime/clock.h:79  in now(); halt
```

**Comment by eyberg** [comment]
do you see this happening on the nightly branch 'ops run -n' ? do you have anything we can reproduce with?

**Comment by sanderssj** [comment]
I tried to reproduce with a go program that frequently called the nanosleep syscall but could not cause it to panic. I have created https://github.com/nanovms/nanos/pull/1786 that updates the check to correct the condition and print out a message instead of panicking. I suspect that if the vm has significant frequency error then it might be easier to trip the problem, so the added error message contains information useful for debugging that. If you see the message, please let us know!

**Comment by zeroecco** [comment]
Awesome, thank you very much!
