### ISSUE TITLE
syslog not reliably pushing logs to Rsyslog server

### ISSUE THREAD

**Issue by zeroecco** [nanovms/nanos#1836]
# Summary
I setup a basic rsyslog server to consume logs from unikernel instances in our production infrastructure.  I have noticed that on first start and when the unikernel crashes are completely missing from the rsyslog server.

specifically the "I crashed" logs
```
...
time="2023-03-31T18:22:19Z" level=fatal msg="disconnected from cluster"
...
```

and the start logs:

```
en1: assigned 10.0.1.7
{"level":"info","msg":"..."}
en1: assigned FE80::38:1BFF:FE70:68A9
```

basic configs are as you would want and once everything is up and stable, logs flow in. I just really need the system crash and start logs to give my dev team confidence in debugging a uniernel in  a production setting

**Comment by eyberg** [comment]
I'd say there are 2 issues here:

1) 'crash logs' - this is a panic that is not flushing before everything dies

2) start - we would need some more information on this just to verify - but is this a local rsyslog that is on the same machine as ops/kvm or is it across the network? is it an ip or dns? regardless of what it is we'd just need to ensure to buffer this

**Comment by francescolavra** [comment]
Regarding the issue of start logs, our syslog klib does buffer outgoing messages, so any message output by the application before the network is up should be eventually delivered to the rsyslog server.
A case where there might be dropped packets is if the application prints many messages in short succession during startup: since the network stack needs to do an initial ARP query in order to retrieve the MAC address to be used for packets with a given destination, if many such packets are sent to the same destination before a response to the ARP query is received, the ARP driver queues only a limited number (currently 3) of them. The result is that from the initial burst of messages, only the most 3 recent ones are delivered.

**Comment by eyberg** [comment]
also, fyi, in the case of a program starting up and shutting down too fast (not sure if that's what is happening here) - there's a user option to make the user program wait exec_wait_for_ip4_secs  - https://github.com/nanovms/nanos/pull/1819

**Comment by zeroecco** [comment]
> I'd say there are 2 issues here:
> 
> 1. 'crash logs' - this is a panic that is not flushing before everything dies
> 2. start - we would need some more information on this just to verify - but is this a local rsyslog that is on the same machine as ops/kvm or is it across the network? is it an ip or dns? regardless of what it is we'd just need to ensure to buffer this

Correct on #1. Application was dying to a transient issue in the infra, nothing technically wrong with the unikernel itself. Devs couldn't figure it out cause the stack trace was missing. 

2. this is over the LAN. we are using IP addresses for the moment, but want to move to DNS as soon as we can.

**Comment by francescolavra** [comment]
https://github.com/nanovms/nanos/pull/1837 fixes both issues (missing start logs and missing crash logs).
