### ISSUE TITLE
hot reload / upgrade nanovm?

### ISSUE THREAD

**Issue by unusualevent** [nanovms/nanos#1907]
Is it possible to write a new image to a running nanovm, and hot reload the kernel into the new one?

or have the code able to update itself?

managing changing IPs on the upstream systems every time a deploy creates a new cloud instance is a pain (with the state nanovms/ops is in as far as cloud provider API support), being able to upgrade in place would be neat :)

**Comment by eyberg** [comment]
it'd be good to get some more info on your current setup - can you expand a bit on your usecase/setup?

are you utilizing dns at all to point at these instances? are there other instances that are wanting a known good ip/cname? ops currently does have support for updating dns records on new instance creates but we could expand that as well

it sounds like the issue at hand has more to deal with being able to deploy new images but keeping the ip/dns the same; there are probably better methods to deal with this if we can paint the usage a bit more

**Comment by unusualevent** [comment]
So I use Fastly to define a service, and I use the JSON output of the vultr provider to get the instance's IP. Vultr doesn't let you keep the same IP during an image restore, it's a fundamentally new VPS instance.

**Comment by rinor** [comment]
@unusualevent is [Vultr Reserved IPs](https://www.vultr.com/docs/vultr-reserved-ips) feasible/acceptable on your side?

**Comment by unusualevent** [comment]
@rinor possibly, I could try building that into ops, if the vultr golang SDK allows it.

I have no clue what semantics would want to be used for that sort of thing.

Maybe the google SDKs or the AWS ones are in use on ops for using a defined reserved IP?

**Comment by eyberg** [comment]
yeh it looks like we have statics for aws && gcp but not vultr yet - although we should be able to add that easily, so that's one option

the other thing I was alluding to was if you're using dns at the same provider ops has a flag '-d' to update the domain name -although I think only aws and gcp have support for this - if this is a solution for you we can add it to vultr as well

https://docs.ops.city/ops/configuration#cloudconfig.domain_name

finally, i'd also be open to adding 3rd party dns additions (as possibly some sort of plugin/hook) to ops for situations like yours where you have an instance on one provider but want to update dns somewhere else (which is fairly common)

**Comment by eyberg** [comment]
we added in static ip support for vultr here https://github.com/nanovms/ops/issues/1502

**Comment by unusualevent** [comment]
sweet. I can give that static IP stuff a spin. If not I'll look into adding fastly-cli (https://github.com/fastly/go-fastly/blob/main/EXAMPLES.md) - or using the json output of vultr to set it. Not sure what structure you'd want dns plugins/hooks to be in ops.

**Comment by eyberg** [comment]
also just added the initial dns support here, https://github.com/nanovms/ops/pull/1508 , I don't think we have any strong opinions on what a potential plugin system might look like right yet since it doesn't exist other than the main goal of being able to load the code w/out forcing it onto other users
