### ISSUE TITLE
eval firecracker

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#483]
@mkhon noted in the rollup that it should prob. just work minus some subbing of things out - worth trying it out and seeing what it spits out as

**Comment by francescolavra** [comment]
Branch https://github.com/nanovms/nanos/tree/feature/firecracker has preliminary (incomplete) support for Firecracker, in that the kernel supports being booted directly from the hypervisor, in 64-bit mode and with paging enabled (with physical memory identity-mapped), without going through stage 1 and stage 2.
If the kernel detects that the hypervisor passed to it the standard Linux boot parameter structure (as Firecracker does), it extracts memory information from this structure, sets up an initial set of page tables to map the kernel code address space, jumps to the virtual address space, then sets up the page tables in the same way as stage2 does, then continues the boot sequence as normal.
Firecracker exposes to the guest VirtIO devices over MMIO transport, not over PCI, and since support for VirtIO devices over MMIO is missing, the kernel reaches the runloop (the serial console works) but is unable to detect storage and network devices.

**Comment by francescolavra** [comment]
Command line: `firecracker-v0.21.1-x86_64 --api-sock /tmp/firecracker.socket --config-file vm_config.json`
```
francesco@ubuntu:~$ cat vm_config.json 
{
  "boot-source": {
    "kernel_image_path": "/usr/src/nanos/output/stage3/bin/stage3.img",
    "boot_args": ""
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "path_on_host": "/usr/src/nanos/output/image/disk.raw",
      "is_root_device": true,
      "is_read_only": false
    }
  ],
  "machine-config": {
    "vcpu_count": 1,
    "mem_size_mib": 1024,
    "ht_enabled": false
  }
```

**Comment by eyberg** [comment]
this isn't a huge priority so I wouldn't take any drastic measures right now but it's my understanding that mmio is much slower @francescolavra ? if that's true i'm wondering if the firecracker team is going to mv to something diff in the future - if so then no point in adding it just for that - also - in your commit the nx bit was flipped - was there a reason why?

**Comment by wjhun** [comment]
It sounds like the existing virtio on MMIO standard supports a single interrupt with no MSI analog. There are proposals to expand the interface / add a feature bit for MSI:

https://lwn.net/Articles/808235/
https://lkml.org/lkml/2020/1/5/75
https://lkml.org/lkml/2020/1/9/459

From the virtio spec it sounds like supporting MMIO will require using device trees for probing and some changes to register accesses:

> Virtual environments without PCI support (a common situation in embedded devices models) might use
simple memory mapped device (“virtio-mmio”) instead of the PCI device.
The memory mapped virtio device behaviour is based on the PCI device specification. Therefore most operations including device initialization, queues configuration and buffer transfers are nearly identical. Existing
differences are described in the following sections.

**Comment by francescolavra** [comment]
Indeed MMIO is significantly slower than PCI; in minimalistic VM hosts such as Firecracker (and also Qemu microvm) the focus is on boot time minimization for short-lived VMs, rather than run time I/O performance, and not having PCI support allows using lightweight hypervisors and kernels that can boot in a fraction of seconds.
It appears the drive for improving I/O performance is leading toward enhancing the MMIO spec with new features (as @wjhun noted), rather than moving to a different transport.

As for the NXE bit, it is not actually being flipped, I just moved the code that sets this bit from the end of stage2 to the beginning of stage3, so that this step is not skipped when the VM is booted directly from stage3.

**Comment by francescolavra** [comment]
#1213 implements full support for Firecracker. Example Firecracker configuration file with network device support:
```
{
  "boot-source": {
    "kernel_image_path": "/usr/src/nanos/output/stage3/bin/stage3.img",
    "boot_args": "console=ttyS0 reboot=k panic=1 pci=off"
  },
  "drives": [
    {
      "drive_id": "rootfs",
      "path_on_host": "/usr/src/nanos/output/image/disk.raw",
      "is_root_device": true,
      "is_read_only": false
    }
  ],
  "network-interfaces": [
    {
      "iface_id": "eth0",
      "guest_mac": "AA:FC:00:00:00:01",
      "host_dev_name": "tap0"
    }
  ],
  "machine-config": {
    "vcpu_count": 1,
    "mem_size_mib": 1024,
    "ht_enabled": false
  }
}
```
In the above file, "tap0" is the name of the network interface that will be used for communication between guest and host. It must be created before running Firecracker, e.g. with:
```
sudo ip tuntap add dev tap0 mode tap
sudo ip addr add 10.0.2.1/24 dev tap0
sudo ip link set tap0 up
```
If there is no bridge setup, a DHCP server must be running in the host and listening on the tap0 interface, e.g. with `sudo dhcpd -f -d tap0`. Alternatively, the kernel can be configured with a static IP address.

**Comment by eyberg** [comment]
this now works - i'm going to follow up w/some docs
