### ISSUE TITLE
erlang otp 20 requires a patch for exec *not* a priority

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#559]
so lo and behold erlang actually wants this pretty bad - we could maybe backport to a otp 19 release but I don't know how much crap that is new (eg: elixir, rabbitmq, etc.) that would want otp 20

anyways - this is super nichy and I wouldn't spend anytime on this until we actually get a request from someone that will pay us money to make it happen

```
eyberg@s1:~/hir$ cat config.json
{
  "Env": {
    "HOME": "/",
    "ROOTDIR": "/usr/lib/erlang",
    "BINDIR": "/usr/lib/erlang/erts-10.2.4/bin",
    "EMU": "beam",
    "PROGNAME": "hi"
  },

  "Args": ["/usr/lib/erlang/erts-10.2.4/bin/erlexec", "-noshell", "-s", "hi", "start", "-s", "init", "stop", "+S", "1"],

  "Files": ["hi.beam"],
  "MapDirs": {"/usr/lib/erlang/*": "/usr/lib/erlang" }

}
```

```
eyberg@s1:~/hir$ ops run -c config.json erlexec
Finding dependent shared libs
[/usr/lib/erlang/erts-10.2.4/bin/erlexec -noshell -s hi start -s init stop -smp disable]
booting /home/eyberg/.ops/images/image ...
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
Argument '-smp disable' not supported. Use "+S 1" instead.
```

```
 cat hi.erl
% hi program
-module(hi).
-export([start/0]).

start() ->
    io:fwrite("Hello, world!\n").
```

```
eyberg@s1:~/hir$ ops run -c config.json -d erlexec
Finding dependent shared libs
[/usr/lib/erlang/erts-10.2.4/bin/erlexec -noshell -s hi start -s init stop +S 1]
booting /home/eyberg/.ops/images/image ...
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
....*snip*....
1 open: "/proc/cpuinfo", flags 80000, mode ffffff98
 1 "/proc/cpuinfo" - not found
 1 direct return: -2
 1 time
 1 direct return: 1551226890
 1 sched_getaffinity
 1 direct return: 0
 1 lstat
 1 name /sys, stat 0000000010263ba90
 1 direct return: -2
 1 lstat
 1 name /sys, stat 0000000010263ba90
 1 direct return: -2
 1 execve
 1 nosyscall execve
 1 write
erlexec: Error 38 executing '/usr/lib/erlang/erts-10.2.4/bin/beam.smp'.
 1 direct return: 72
 1 exit_group
```

**Comment by eyberg** [comment]
smp shouldn't be a road blocker anymore, however, first thing erlexec tries to do is exec out - it appears osv just patched that https://github.com/cloudius-systems/osv-apps/blob/master/erlang/epmd.patch#L89

**Comment by eyberg** [comment]
https://github.com/nanovms/erlang

**Comment by francescolavra** [comment]
Using the latest Erlang/OTP version, i.e. OTP 23.0, the patch for osv doesn't apply, so I had to tweak it a bit in order for it to apply, but with the patch Erlang still doesn't work: it fails when it tries to load the BEAM emulator via dlopen(). The reason for the failure is that dlopen() only works for shared libraries, and not for plain executable files (not sure how the osv patch could have worked, I assume they were using a patched libdl); so I changed the compiler and linker flags in order to build BEAM as a shared library, but then it fails with error `This run-time was supposed be compiled with all code below 2Gb, but the instruction 'allocate_tt' is located at 00007f45697182b6`. So BEAM doesn't like it when it's compiled as a shared library.
I think the best solution would be to incorporate the functionality of erlexec (which is the entry point to run a compiled Erlang program) into the BEAM executable, maybe making erlexec a symbolic link to BEAM, so that BEAM could check argv[0] and act accordingly. Another thing we need is to incorporate the port mapper daemon (epmd) into the BEAM executable as well (or alternatively make it a shared library), so that it can be run as a thread of BEAM instead of as a separate process.

**Comment by francescolavra** [comment]
The changes at https://github.com/nanovms/erlang/pull/1 make the Erlang runtime system able to run on Nanos: only one executable file (erlexec) is needed, and if an Erlang node is started in distributed mode (e.g. with the `-sname name@host` command line option) the EPMD is spawned as an internal thread instead of as a separate process.
Running a node in distributed mode requires the loopback interface (#1187).
#1188 prevents (non-fatal) errors related to unimplemented socket options.

**Comment by eyberg** [comment]
awesome! hw works!
