### ISSUE TITLE
fs doesn't see utf-8 files

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#567]
i was looking to verify this -> 

https://github.com/nanovms/nanos/issues/389

and while that seems to work for whatever reason tfs doesn't seem to see it ->

```
eyberg@s1:~/g$ ops run -c config.json g
Finding dependent shared libs
booting /home/eyberg/.ops/images/image ...
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
open /✔.txt: no such file or directory
/
/dev
/dev/null
/dev/urandom
/etc
/etc/resolv.conf
/g
/kernel
/proc
/proc/sys
/proc/sys/kernel
/proc/sys/kernel/hostname
/some.txt
exit_group
exit status 1
eyberg@s1:~/g$ cat config.json
{
  "Files": ["✔.txt", "some.txt"]
}
```

```
eyberg@s1:~/g$ cat main.go
package main

import (
    "fmt"
    "io/ioutil"
    "os"
    "path/filepath"
)

func main() {

    dat, err := ioutil.ReadFile("/✔.txt")
    if err != nil {
        fmt.Println(err)
    }

    fmt.Print(string(dat))

    var files []string

    root := "/"
    err = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
        files = append(files, path)
        return nil
    })
    if err != nil {
        panic(err)
    }
    for _, file := range files {
        fmt.Println(file)
    }

}
```

**Comment by x64k** [comment]
This is a little unexpected -- I thought it was a simple case of higher-level FS code not being unicode-aware, but I think the problem is slightly different. It seems that the `buffer` structure built in `resolve_cstring` doesn't contain the "right" value (or, more accurately, calling `intern` on that buffer doesn't return the right value). Looking up after that value fails, of course.

I gotta wrap my head around the tuple code but I should have a fix reasonably soon.
