### ISSUE TITLE
stage2: implement kern_sleep()

### ISSUE THREAD

**Issue by mkhon** [nanovms/nanos#923]
Is ideally required for ATA support in stage2 (but currently stage2 ATA works with zero timeouts in AWS T2 and qemu).

Porting existing clock.c/hpet.c and/or adding rdtsc (without dependency on KVM vclock) should be enough.

I think stage2 implementation should not depend on any PV clock/time so remaining options are:
- rdtsc
- hpet

**Comment by wjhun** [comment]
Xen cpuid leaves offer some TSC scaling info. This could be easily mined in stage2 without requiring Xen platform support per se. This may be good enough to get ballpark timeouts in stage2.

**Comment by eyberg** [comment]
can we close @wjhun ?

**Comment by wjhun** [comment]
> can we close @wjhun ?

We're getting by without this, but it still ought to be implemented.

This would make a good first issue.

**Comment by estherlyoon** [comment]
@wjhun Would it be possible for me to pick up working on this issue?

**Comment by wjhun** [comment]
@estherlyoon I'm actually going to close this one. An uncalibrated kern_sleep has been added in stage2 since this was last updated, and that suffices for our needs at the moment. Getting an accurate timer in stage2 would require some access to pvclock or some other means of calibrating the timer, which doesn't seem to be necessary at this point.
