### ISSUE TITLE
Need to expose diagnostic jSON endpoints from kernel

### ISSUE THREAD

**Issue by tijoytom-zz** [nanovms/nanos#94]
Can be a dedicated thread running to report stats and diag information. External dashboard can do an http get, for example
/diag/threads
/diag/cpu
/diag/memory
/diag/disk
/diag/uptime..
and so on...

**Comment by prologic** [comment]
Why not just provide the stats/metrics on the image's filesystem (tfs?) and make exposing metrics/stats the user's problem as part of their application design. Much like stuff you can scrape out of the `/sys` linux vfs? I personally would rather my application baked into nanos didn't have a builtin web server at all if I didn't want/need it.

**Comment by eyberg** [comment]
no worries - we'll never turn on a webserver by default for anything - having said that we do have debugging flags to enable export of various metrics and there is a http interface for that (explicitly turned off and only avail w/debugging flags which ops doesn't even have yet); I highly doubt we'll end up stuffing this into a fs though since there is a lack of user interactivity w/these
